name: CI

on:
  push:
    branches:
      - "main"
  pull_request_target:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install modules
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
