name: CI

on: [push, pull_request_target]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install modules
        run: yarn

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests
        run: yarn test
